import React, { createContext, useContext, useState, useEffect } from 'react';

interface LanguageContextType {
  currentLanguage: string;
  setLanguage: (lang: string) => void;
  t: (key: string) => string;
  currencies: Record<string, string>;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

const translations: Record<string, Record<string, string>> = {
  en: {
    siteName: 'Adventureseekerz',
    tagline: 'Immersive experiences in your language',
    bookNow: 'Book Now',
    learnMore: 'Learn More',
    ourTours: 'Our Tours',
    meetGuides: 'Meet Our Guides',
    reviews: 'What Our Guests Say',
    blog: 'Travel Blog',
    b2bPortal: 'B2B Portal',
    contact: 'Contact Us',
    selectLanguage: 'Select Language',
    selectDate: 'Select Date',
    selectTime: 'Select Time',
    participants: 'Participants',
    totalPrice: 'Total Price',
    bookTour: 'Book This Tour',
    tourDetails: 'Tour Details',
    highlights: 'Highlights',
    itinerary: 'Itinerary',
    meetingPoint: 'Meeting Point',
    cancellationPolicy: 'Cancellation Policy',
    duration: 'Duration',
    groupSize: 'Max Group Size',
    price: 'Price',
    languages: 'Languages',
    speaksLanguages: 'Speaks',
    specialties: 'Specialties',
    experience: 'Years of Experience',
    rating: 'Rating',
    readBio: 'Read Full Bio',
    bookWithGuide: 'Book with this Guide',
    customerName: 'Your Name',
    email: 'Email',
    phone: 'Phone',
    specialRequests: 'Special Requests',
    confirmBooking: 'Confirm Booking',
    allTours: 'All Tours',
    filterByTheme: 'Filter by Theme',
    filterByLanguage: 'Filter by Language',
    featuredGuides: 'Featured Guides',
    verifiedReview: 'Verified Review',
    groupBookings: 'Group Bookings',
    travelAgents: 'For Travel Agents',
    companyName: 'Company Name',
    apply: 'Apply Now',
    send: 'Send Message',
    message: 'Message',
    hours: 'hours',
    from: 'from',
    person: 'per person',
  },
  es: {
    siteName: 'Adventureseekerz',
    tagline: 'Experiencias inmersivas en tu idioma',
    bookNow: 'Reservar Ahora',
    learnMore: 'Más Información',
    ourTours: 'Nuestros Tours',
    meetGuides: 'Conoce a Nuestros Guías',
    reviews: 'Lo Que Dicen Nuestros Huéspedes',
    blog: 'Blog de Viajes',
    b2bPortal: 'Portal B2B',
    contact: 'Contacto',
    selectLanguage: 'Seleccionar Idioma',
    selectDate: 'Seleccionar Fecha',
    selectTime: 'Seleccionar Hora',
    participants: 'Participantes',
    totalPrice: 'Precio Total',
    bookTour: 'Reservar Este Tour',
    tourDetails: 'Detalles del Tour',
    highlights: 'Aspectos Destacados',
    itinerary: 'Itinerario',
    meetingPoint: 'Punto de Encuentro',
    cancellationPolicy: 'Política de Cancelación',
    duration: 'Duración',
    groupSize: 'Tamaño Máximo del Grupo',
    price: 'Precio',
    languages: 'Idiomas',
    speaksLanguages: 'Habla',
    specialties: 'Especialidades',
    experience: 'Años de Experiencia',
    rating: 'Calificación',
    readBio: 'Leer Biografía Completa',
    bookWithGuide: 'Reservar con este Guía',
    customerName: 'Tu Nombre',
    email: 'Correo Electrónico',
    phone: 'Teléfono',
    specialRequests: 'Solicitudes Especiales',
    confirmBooking: 'Confirmar Reserva',
    allTours: 'Todos los Tours',
    filterByTheme: 'Filtrar por Tema',
    filterByLanguage: 'Filtrar por Idioma',
    featuredGuides: 'Guías Destacados',
    verifiedReview: 'Reseña Verificada',
    groupBookings: 'Reservas de Grupo',
    travelAgents: 'Para Agentes de Viajes',
    companyName: 'Nombre de la Empresa',
    apply: 'Aplicar Ahora',
    send: 'Enviar Mensaje',
    message: 'Mensaje',
    hours: 'horas',
    from: 'desde',
    person: 'por persona',
  },
  fr: {
    siteName: 'Adventureseekerz',
    tagline: 'Expériences immersives dans votre langue',
    bookNow: 'Réserver Maintenant',
    learnMore: 'En Savoir Plus',
    ourTours: 'Nos Visites',
    meetGuides: 'Rencontrez Nos Guides',
    reviews: 'Ce Que Disent Nos Clients',
    blog: 'Blog de Voyage',
    b2bPortal: 'Portail B2B',
    contact: 'Contact',
    selectLanguage: 'Choisir la Langue',
    selectDate: 'Choisir la Date',
    selectTime: 'Choisir l\'Heure',
    participants: 'Participants',
    totalPrice: 'Prix Total',
    bookTour: 'Réserver Cette Visite',
    tourDetails: 'Détails de la Visite',
    highlights: 'Points Forts',
    itinerary: 'Itinéraire',
    meetingPoint: 'Point de Rencontre',
    cancellationPolicy: 'Politique d\'Annulation',
    duration: 'Durée',
    groupSize: 'Taille Maximale du Groupe',
    price: 'Prix',
    languages: 'Langues',
    speaksLanguages: 'Parle',
    specialties: 'Spécialités',
    experience: 'Années d\'Expérience',
    rating: 'Note',
    readBio: 'Lire la Bio Complète',
    bookWithGuide: 'Réserver avec ce Guide',
    customerName: 'Votre Nom',
    email: 'Email',
    phone: 'Téléphone',
    specialRequests: 'Demandes Spéciales',
    confirmBooking: 'Confirmer la Réservation',
    allTours: 'Toutes les Visites',
    filterByTheme: 'Filtrer par Thème',
    filterByLanguage: 'Filtrer par Langue',
    featuredGuides: 'Guides en Vedette',
    verifiedReview: 'Avis Vérifié',
    groupBookings: 'Réservations de Groupe',
    travelAgents: 'Pour les Agents de Voyage',
    companyName: 'Nom de l\'Entreprise',
    apply: 'Postuler Maintenant',
    send: 'Envoyer le Message',
    message: 'Message',
    hours: 'heures',
    from: 'à partir de',
    person: 'par personne',
  },
  it: {
    siteName: 'Adventureseekerz',
    tagline: 'Esperienze coinvolgenti nella tua lingua',
    bookNow: 'Prenota Ora',
    learnMore: 'Scopri di Più',
    ourTours: 'I Nostri Tour',
    meetGuides: 'Incontra le Nostre Guide',
    reviews: 'Cosa Dicono i Nostri Ospiti',
    blog: 'Blog di Viaggio',
    b2bPortal: 'Portale B2B',
    contact: 'Contattaci',
    selectLanguage: 'Seleziona Lingua',
    selectDate: 'Seleziona Data',
    selectTime: 'Seleziona Ora',
    participants: 'Partecipanti',
    totalPrice: 'Prezzo Totale',
    bookTour: 'Prenota Questo Tour',
    tourDetails: 'Dettagli del Tour',
    highlights: 'Punti Salienti',
    itinerary: 'Itinerario',
    meetingPoint: 'Punto d\'Incontro',
    cancellationPolicy: 'Politica di Cancellazione',
    duration: 'Durata',
    groupSize: 'Dimensione Massima del Gruppo',
    price: 'Prezzo',
    languages: 'Lingue',
    speaksLanguages: 'Parla',
    specialties: 'Specialità',
    experience: 'Anni di Esperienza',
    rating: 'Valutazione',
    readBio: 'Leggi la Biografia Completa',
    bookWithGuide: 'Prenota con questa Guida',
    customerName: 'Il Tuo Nome',
    email: 'Email',
    phone: 'Telefono',
    specialRequests: 'Richieste Speciali',
    confirmBooking: 'Conferma Prenotazione',
    allTours: 'Tutti i Tour',
    filterByTheme: 'Filtra per Tema',
    filterByLanguage: 'Filtra per Lingua',
    featuredGuides: 'Guide in Evidenza',
    verifiedReview: 'Recensione Verificata',
    groupBookings: 'Prenotazioni di Gruppo',
    travelAgents: 'Per Agenti di Viaggio',
    companyName: 'Nome dell\'Azienda',
    apply: 'Candidati Ora',
    send: 'Invia Messaggio',
    message: 'Messaggio',
    hours: 'ore',
    from: 'da',
    person: 'a persona',
  },
  de: {
    siteName: 'Adventureseekerz',
    tagline: 'Immersive Erlebnisse in Ihrer Sprache',
    bookNow: 'Jetzt Buchen',
    learnMore: 'Mehr Erfahren',
    ourTours: 'Unsere Touren',
    meetGuides: 'Treffen Sie Unsere Guides',
    reviews: 'Was Unsere Gäste Sagen',
    blog: 'Reiseblog',
    b2bPortal: 'B2B-Portal',
    contact: 'Kontakt',
    selectLanguage: 'Sprache Wählen',
    selectDate: 'Datum Wählen',
    selectTime: 'Zeit Wählen',
    participants: 'Teilnehmer',
    totalPrice: 'Gesamtpreis',
    bookTour: 'Diese Tour Buchen',
    tourDetails: 'Tour-Details',
    highlights: 'Höhepunkte',
    itinerary: 'Reiseverlauf',
    meetingPoint: 'Treffpunkt',
    cancellationPolicy: 'Stornierungsbedingungen',
    duration: 'Dauer',
    groupSize: 'Max. Gruppengröße',
    price: 'Preis',
    languages: 'Sprachen',
    speaksLanguages: 'Spricht',
    specialties: 'Spezialitäten',
    experience: 'Jahre Erfahrung',
    rating: 'Bewertung',
    readBio: 'Vollständige Biografie Lesen',
    bookWithGuide: 'Mit diesem Guide Buchen',
    customerName: 'Ihr Name',
    email: 'E-Mail',
    phone: 'Telefon',
    specialRequests: 'Besondere Wünsche',
    confirmBooking: 'Buchung Bestätigen',
    allTours: 'Alle Touren',
    filterByTheme: 'Nach Thema Filtern',
    filterByLanguage: 'Nach Sprache Filtern',
    featuredGuides: 'Empfohlene Guides',
    verifiedReview: 'Verifizierte Bewertung',
    groupBookings: 'Gruppenbuchungen',
    travelAgents: 'Für Reiseveranstalter',
    companyName: 'Firmenname',
    apply: 'Jetzt Bewerben',
    send: 'Nachricht Senden',
    message: 'Nachricht',
    hours: 'Stunden',
    from: 'ab',
    person: 'pro Person',
  },
  ja: {
    siteName: 'Adventureseekerz',
    tagline: 'あなたの言語で体験する没入型ツアー',
    bookNow: '今すぐ予約',
    learnMore: '詳細を見る',
    ourTours: 'ツアー一覧',
    meetGuides: 'ガイドの紹介',
    reviews: 'お客様の声',
    blog: '旅行ブログ',
    b2bPortal: 'B2Bポータル',
    contact: 'お問い合わせ',
    selectLanguage: '言語を選択',
    selectDate: '日付を選択',
    selectTime: '時間を選択',
    participants: '参加者数',
    totalPrice: '合計金額',
    bookTour: 'このツアーを予約',
    tourDetails: 'ツアー詳細',
    highlights: 'ハイライト',
    itinerary: '旅程',
    meetingPoint: '集合場所',
    cancellationPolicy: 'キャンセルポリシー',
    duration: '所要時間',
    groupSize: '最大グループサイズ',
    price: '料金',
    languages: '言語',
    speaksLanguages: '話せる言語',
    specialties: '専門分野',
    experience: '経験年数',
    rating: '評価',
    readBio: '詳しい経歴を見る',
    bookWithGuide: 'このガイドで予約',
    customerName: 'お名前',
    email: 'メールアドレス',
    phone: '電話番号',
    specialRequests: '特別なリクエスト',
    confirmBooking: '予約を確認',
    allTours: 'すべてのツアー',
    filterByTheme: 'テーマで絞り込む',
    filterByLanguage: '言語で絞り込む',
    featuredGuides: 'おすすめガイド',
    verifiedReview: '確認済みレビュー',
    groupBookings: 'グループ予約',
    travelAgents: '旅行会社の方へ',
    companyName: '会社名',
    apply: '今すぐ申し込む',
    send: 'メッセージを送信',
    message: 'メッセージ',
    hours: '時間',
    from: 'から',
    person: '1人あたり',
  },
  zh: {
    siteName: 'Adventureseekerz',
    tagline: '用您的语言体验沉浸式旅程',
    bookNow: '立即预订',
    learnMore: '了解更多',
    ourTours: '我们的旅游',
    meetGuides: '认识我们的导游',
    reviews: '客户评价',
    blog: '旅游博客',
    b2bPortal: 'B2B门户',
    contact: '联系我们',
    selectLanguage: '选择语言',
    selectDate: '选择日期',
    selectTime: '选择时间',
    participants: '参与人数',
    totalPrice: '总价',
    bookTour: '预订此旅游',
    tourDetails: '旅游详情',
    highlights: '亮点',
    itinerary: '行程',
    meetingPoint: '集合地点',
    cancellationPolicy: '取消政策',
    duration: '时长',
    groupSize: '最大团组规模',
    price: '价格',
    languages: '语言',
    speaksLanguages: '讲',
    specialties: '专长',
    experience: '经验年限',
    rating: '评分',
    readBio: '阅读完整简介',
    bookWithGuide: '与此导游预订',
    customerName: '您的姓名',
    email: '电子邮件',
    phone: '电话',
    specialRequests: '特殊要求',
    confirmBooking: '确认预订',
    allTours: '所有旅游',
    filterByTheme: '按主题筛选',
    filterByLanguage: '按语言筛选',
    featuredGuides: '精选导游',
    verifiedReview: '已验证评论',
    groupBookings: '团体预订',
    travelAgents: '旅行社专区',
    companyName: '公司名称',
    apply: '立即申请',
    send: '发送消息',
    message: '消息',
    hours: '小时',
    from: '从',
    person: '每人',
  },
};

const currencyRates: Record<string, number> = {
  GBP: 1,
  EUR: 1.17,
  USD: 1.27,
  JPY: 193.5,
};

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [currentLanguage, setCurrentLanguage] = useState('en');

  useEffect(() => {
    const stored = localStorage.getItem('preferredLanguage');
    if (stored && translations[stored]) {
      setCurrentLanguage(stored);
    }
  }, []);

  const setLanguage = (lang: string) => {
    setCurrentLanguage(lang);
    localStorage.setItem('preferredLanguage', lang);
  };

  const t = (key: string): string => {
    return translations[currentLanguage]?.[key] || translations.en[key] || key;
  };

  const currencies: Record<string, string> = {
    en: 'GBP',
    es: 'EUR',
    fr: 'EUR',
    it: 'EUR',
    de: 'EUR',
    ja: 'JPY',
    zh: 'USD',
  };

  return (
    <LanguageContext.Provider value={{ currentLanguage, setLanguage, t, currencies }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within LanguageProvider');
  }
  return context;
};

export const convertPrice = (basePrice: number, currency: string): string => {
  const rate = currencyRates[currency] || 1;
  const converted = basePrice * rate;

  const symbols: Record<string, string> = {
    GBP: '£',
    EUR: '€',
    USD: '$',
    JPY: '¥',
  };

  return `${symbols[currency]}${Math.round(converted)}`;
};
